[package]
name = "create_qod_session"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[lib]
crate-type = ["cdylib"]

[workspace]

[dependencies]
wasm-bindgen = "0.2.92"
